sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 3 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 5 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 7 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 9 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 3 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 5 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 7 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 9 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 3 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 5 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 7 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 9 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 3 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 5 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 7 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 9 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 3 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 5 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 7 --gradient_step 10 --grid_size 10;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 9 --gradient_step 10 --grid_size 10;

python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 3 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 5 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 7 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 5 --max_step_syntheticTrajectory 9 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 3 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 5 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 7 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 10 --max_step_syntheticTrajectory 9 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 3 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 5 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 7 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 20 --max_step_syntheticTrajectory 9 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 3 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 5 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 7 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 30 --max_step_syntheticTrajectory 9 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 3 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 5 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 7 --gradient_step 1;
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches';
python run_NS.py --max_episodes_syntheticTrajectory 50 --max_step_syntheticTrajectory 9 --gradient_step 1;


